Royal/urls.py
"""
URL configuration for Royal International School WebApp project.
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('launch.urls') ),
    path('hom/', include('home.urls') ),
 #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    # path('portfolio/', views.portfolio, name='portfolio'),
    path('add/', views.add_blog_post, name='add_blog_post'),

] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

launch/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'launch'
urlpatterns = [
    path('', views.index, name='index'),

] 

home/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=250, null=False, blank=False)
    email = models.EmailField(max_length=250, null=False, blank=False)
    subject = models.CharField(max_length=250)
    message = models.TextField(null=False, blank=False, max_length=1024)

    def __str__(self):
        return self.name


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class BlogPost(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=20)
    content = models.TextField(max_length=1024)
    date_published = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='blog_images/', null=True, blank=True)
    comment = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title

launch/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from .models import BlogPost
from .models import Category
from .models import Contact
from .widgets import CustomClearableFileInput
from django.forms.widgets import TextInput, Textarea


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject', 'message')
        widget = {
            'name': TextInput(attrs={"placeholder": "Your Name"}),
            'email': TextInput(attrs={"placeholder": "Your Email"}),
            'subject': TextInput(attrs={"placeholder": "Subject"}),
            'message': Textarea(attrs={"placeholder": "Your message"}),
        }
    

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = '__all__'
        # fields = ['title', 'content', 'category', 'image']  
        image = forms.ImageField(
            label='Image',
            required=True,
            widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-2'

home/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.conf import settings
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.contrib import messages
import csv
from .forms import ContactForm, BlogPostForm
from .models import BlogPost, Contact    # Import your BlogPost model

# def index(request):
        
#     return render(request, 'home/index.html')


def index(request):
    # Retrieve recent blog posts from the database
    recent_posts = BlogPost.objects.order_by('-date_published')[:3]
    
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():

            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']

            form.save()

            try:
                # Send email code here
                messages.success(request, 'Your message has been sent successfully!')
            except Exception as e:
                messages.error(request, f'Error sending email: {str(e)}')

                # Write form data to CSV
                with open('responses.csv', 'a', newline='') as csvfile:
                    fieldnames = ['Name', 'Email', 'Subject', 'Message']
                    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
                    writer.writerow({'Name': name, 'Email': email, 'Subject': subject, 'Message': message})
                
                # Display error message
                messages.error(request, 'There was an error sending your message. Please try again.')
    else:
        form = ContactForm()

    return render(request, 'home/index.html', {'form': form, 'recent_posts': recent_posts})



def about(request):
    
    return render(request, 'home/about.html')

def programs(request):
    
    return render(request, 'home/programs.html')

def add_blog_post(request):
    if request.method == 'POST':
        form = BlogPostForm(request.POST, request.FILES)  # Include request.FILES
        if form.is_valid():
            form.save()
            messages.success(request, 'Blog post created successfully!')
            return redirect('home:index')  # Redirect to the index page after successful submission
        else:
            messages.error(request, 'Error creating blog post. Please check the form.')
    else:
        form = BlogPostForm()
    return render(request, 'home/add_blog_post.html', {'form': form})

launch/views.py
from django.shortcuts import render, redirect
from django.conf import settings

def index(request):
        
    return render(request, 'launch/index.html')

home/templates/acjhero.html
<section id="ACJ-hero" class="js-fullheight" data-section="home">
    <div class="flexslider js-fullheight">
        <ul class="slides">
            {% block slides %}
             <li style="background-image: url('{% static "Home/images/img_bg_1.jpg" %}');">
                <div class="overlay"></div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3 col-md-pull-3 col-sm-12 col-xs-12 js-fullheight slider-text">
                            <div class="slider-text-inner js-fullheight">
                                <div class="desc" >
                                    <h1 style="font-family: 'Space Grotesk'">Hi! <br><span> <a href="/portfolio" target="_blank" style="text-decoration:none;color:black">The ACJ</a></span></h1>
                                    <h2>With us Tech Emancipation is achievable</h2>
                                     <p><a class="btn btn-primary btn-learn" href="#" download>Download CV <i class="icon-download"></i></a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
               </li>
              <li style="background-image: url('{% static "Home/images/img_bg_2.jpg" %}');background-position: 10px 10px;">
                <div class="overlay"></div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3 col-md-pull-3 col-sm-12 col-xs-12 js-fullheight slider-text">
                            <div class="slider-text-inner">
                                <div class="desc">
                                    <h1 style="color:white; font-family: 'Space Grotesk'">I am a<br> Data Analyst</h1>
                                     <h2 style="color:white" >Where there is Data, <span> <a href="/portfolio" target="_blank" style="text-decoration:none;color:white">The ACJ</a></span> will make sense of it</h2>
                                     <p><a class="btn btn-primary btn-learn" style="color:white;border: 1px solid #fff">View Portfolio <i class="icon-briefcase"></i></a></p>
                                 </div>
                            </div>
                        </div>
                    </div>
                </div>
             </li>
               <li style="background-image: url('{% static "Home/images/img_bg_3.jpg" %}');">
                 <div class="overlay"></div>
                 <div class="container-fluid">
                     <div class="row">
                         <div class="col-md-6 col-md-offset-3 col-md-pull-3 col-sm-12 col-xs-12 js-fullheight slider-text">
                            <div class="slider-text-inner">
                                <div class="desc">
                                    <h1 style="font-family: 'Space Grotesk'">I am a<br> Web Developer</h1>
                                      <h2>Imagine it, <span> <a href="/portfolio" target="_blank" style="text-decoration:none;color:black">The ACJ</a></span> will make it real</h2>
                                      <p><a class="btn btn-primary btn-learn">View Portfolio <i class="icon-briefcase1"></i></a></p>
                                  </div>
                             </div>
                         </div>
                     </div>
                 </div>
               </li>
            {% endblock %}								
           </ul>
    </div>
</section> <!-- end:section(ACJ-hero) -->






      <!-- section -->
      <section class="main_full banner_section_top">
        <div class="container-fluid">
          <div class="row">
             <div class="full">
                  <div class="slider_banner">
                    <img class="img-responsive" src="{% static 'home/images/slider_img.png' %}" alt="#" />
                      <div class="slide_cont">
                        <div class="slider_cont_inner">
                          <h3>Welcome To Royal International Schools' Website</h3>
                        <p>Making rural children assets to their community and the society at large</p></p>
                        </div>
                      </div>
                  </div>
                </div>
          </div>
        </div>
      </section>
      <!-- end section -->

home/templates/home/about.html
{% extends  "home/base.html" %} 
{% load static %}
{% block sections %}

   {% comment %} <section class="main_full inner_page">
      <div class="container-fluid">
        <div class="row">
           <div class="full">
             <h3>About us</h3>    
           </div>
        </div>
      </div>
   </section> {% endcomment %}
    <!-- end section -->
  
   <!-- about section -->
    <section class="layout_padding section about_dottat">
       <div class="container">
          <div class="row">
             <div class="col-lg-12 text_align_center">
                <div class="full">
                   <h3 class="about mt-1"> About us  <img src="{% static 'home/images/logo.png' %}" class="lg_img"  alt="Royal International School Ogoli" /></h3>
                   <p class="large"><br>
                      At Royal International School, we believe that every child deserves access to modern education, regardless of their background. Our curriculum is designed to provide students with a comprehensive and contemporary learning experience, incorporating the latest teaching methodologies and technologies. Our dedicated teachers are not only highly qualified but also deeply committed to making education affordable for all, generously subsidizing the cost to ensure that no child is left behind.
                      <br>                        
                      Our mission is to empower the next generation with the knowledge and skills they need to thrive in an ever-changing world. We strive to create a nurturing and inclusive environment where students can explore their potential, develop critical thinking, and become responsible global citizens.
                      <br>                        
                      Join us at Royal International School, where we are building a brighter future, one student at a time</p>
                </div>
             </div>
             <div class="col-md-12">
                <div class="about_img margin_top_30  text_align_center">
                   <img src="{% static 'home/images/ab_img.png' %}" alt="#" />
                </div>
             </div>
          </div>
       </div>
    </section>
</section>
{% endblock sections %}

      
      <!-- section -->


      <!-- end about section -->

      <!-- section -->
      {% comment %} <section class="layout_padding section">
         <div class="container">
            <div class="row">
               <div class="col-lg-12 text_align_center">
                  <div class="full heading_s1">
                     <h2>Our Courses</h2>
                  </div>
                  <div class="full">
                     <p class="large">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo</p>
                  </div>
               </div>
            </div>
            <div class="row">

              <div class="col-md-4 text_align_center">
                 <div class="cours">
                   <img class="img-responsive" src="images/cour1.png" alt="#" />
                 </div>
                 <h3>Design</h3>
                 <p>adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in re</p>
              </div>  

              <div class="col-md-4 text_align_center">
                 <div class="cours">
                   <img class="img-responsive" src="images/cour2.png" alt="#" />
                 </div>
                 <h3>Coding</h3>
                 <p>adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in re</p>
              </div> 

              <div class="col-md-4 text_align_center">
                 <div class="cours">
                   <img class="img-responsive" src="images/cour3.png" alt="#" />
                 </div>
                 <h3>Javascript</h3>
                 <p>adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in re</p>
              </div> 

            </div>
            <div class="row">
               <div class="col-md-12">
                  <div class="full center">
                      <a class="blue_bt" href="#">Read More</a>
                  </div>
               </div>
            </div>
         </div>
      </section> {% endcomment %}
      <!-- end section -->
  
      <!-- section -->
      {% comment %} <section class="section blue_pattern_bg" style="background-color: #3b3bff;">
         <div class="container">
            <div class="row">
               <div class="col-md-6">
                  <div class="full">
                     <h4>Subscribe Now to Our Newsletter !</h4>
                     <p>adipiscing elit, sed do eiusmod tempor incididunt ut<br>labore et dolore magna aliqua.</p>
                  </div>
               </div>
               <div class="col-md-6">
                 <div class="form_subribe">
                    <form>
                       <input type="email" name="email" placeholder="Enter Your Email" />
                       <button>Subscribe</button>
                    </form>
                 </div>
               </div>
            </div>
         </div>
      </section> {% endcomment %}
      <!-- end section -->

home/templates/home/add_blog_post.html
<!-- add_blog_post.html -->

{% extends "home/base.html" %}
{% load static %}
    {% block sections %}
    <section style="margin-left:40px">
        <div>
            <div class="row">
                <div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box">
                    <span class="heading-meta">Make a Post</span>
                    <h2 class="ACJ-heading">Publish</h2>
                </div><br><br>
            </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_title">Title:</label>
                        {{ form.title }}
                    </div><br><br>
                    <div class="form-group">
                        <label for="id_content">Content:</label>
                        {{ form.content }}
                    </div><br><br>
                                                    
                        <div class="form-group">
                            <label for="id_image">Image:</label>
                            <div class="image-upload">
                                <label for="file-input">
                                    <i class="icon-cloud-upload2" style="margin:auto"></i> Choose File
                                </label>
                                <input id="file-input" type="file" name="image" accept="image/*" onchange="previewImage(event)">
                            </div>
                            <img id="preview" src="#" alt="Image Preview" style="display: none; max-width: 100%;">
                            <p class="drag-drop-text">Drag & drop an image here or click to upload.</p>
                        </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary btn-send-message" value="Upload">
                    </div>
                </form>
            </div>
        </div>               
    </section>
    {% endblock sections %}
    {% block Js %}
    <script>
        function previewImage(event) {
            var reader = new FileReader();
            reader.onload = function() {
                var output = document.getElementById('preview');
                output.src = reader.result;
                output.style.display = 'block';
            };
            reader.readAsDataURL(event.target.files[0]);
        }
    </script>
    {% endblock Js %}
                    

</body>

home/templates/home/custom_widget_templates/custom_clearable_file_input.html
{% if widget.is_initial %}
<p>{{ widget.initial_text }}:</p>
<a href="{{ widget.value.url }}">
    <img width="96" height="96" class="rounded shadow-sm" src="{{ widget.value.url }}">
</a>
{% if not widget.required %}
<div class="custom-control custom-checkbox mt-2">
    <input class="custom-control-input" type="checkbox" name="{{ widget.checkbox_name }}" id="{{ widget.checkbox_id }}">
    <label class="custom-control-label text-danger"
        for="{{ widget.checkbox_id }}">{{ widget.clear_checkbox_label }}</label>
</div>
{% endif %}<br>
{{ widget.input_text }}
{% endif %}
<span class="btn btn-black rounded-2 btn-file">
    Select Image <input id="new-image" type="{{ widget.type }}" name="{{ widget.name }}"
        {% include "django/forms/widgets/attrs.html" %}>
</span>
<strong>
    <p class="text-danger" id="filename"></p>
</strong>

home/templates/home/include/contact.html
<section class="ACJ-contact" data-section="contact">
    <div class="ACJ-narrow-content">
       <div class="row">
          <div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
             <span class="heading-meta">Get in Touch</span>
             <h2 class="ACJ-heading">Contact</h2>
          </div>
       </div>
       <div class="row">
          <div class="col-md-5">
             <div class="ACJ-feature ACJ-feature-sm animate-box" data-animate-effect="fadeInLeft">
                <div class="ACJ-icon">
                   <i class="icon-email"></i>
                </div>
                <div class="ACJ-text">
                   <p><a href="mailto: support@royalintschogoli.com.ng">Mail The RIS</a></p>
                </div>
             </div><br>

             <div class="ACJ-feature ACJ-feature-sm animate-box" data-animate-effect="fadeInLeft">
                <div class="ACJ-icon">
                   <i class="icon-map"></i>
                </div>
                <div class="ACJ-text">
                   <p> Nigeria</p>
                </div>
             </div><br>

             <div class="ACJ-feature ACJ-feature-sm animate-box" data-animate-effect="fadeInLeft">
                <div class="ACJ-icon">
                   <i class="icon-phone"></i>
                </div>
                <div class="ACJ-text">
                   <p><a href="tel:+2349121490555"> Call Us</a></p>
                </div>
             </div><br>
          </div><br><br>
          <div class="col-md-7 col-md-push-1 msg">
             <div class="row">
                <div class="col-md-10 col-md-offset-1 col-md-pull-1 animate-box" data-animate-effect="fadeInRight">
                   <form action="" method="post">
                     {% csrf_token %}
                     {% if messages %}
                        {% for message in messages %}
                         <div class="alert alert-success" role="alert">
                          {{ message }}
                         </div>
                         {% endfor %}
                      {% endif %}
                      <div class="form-group">
                         <input type="text" class="form-control" placeholder="Name" name="name">
                      </div>
                      <div class="form-group">
                         <input type="text" class="form-control" placeholder="Email" name="email">
                      </div>
                      <div class="form-group">
                         <input type="text" class="form-control" placeholder="Subject" name="subject">
                      </div>
                      <div class="form-group">
                         <textarea name="message" id="message" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
                      </div>
                      <div class="form-group">
                         <input type="submit" class="btn btn-primary btn-send-message" value="Send Message">
                      </div>
                   </form>

                </div>
       
             </div>
          </div>
       </div>
    </div>
 </section>

home/templates/home/index.html
{% extends  "home/base.html" %}  
{% load static %}    
     {% block sections %}
    <!-- about section -->
    <section class="layout_padding section about_dottat">
      <div class="container">
         <div class="row">
            <div class="col-lg-12 text_align_center">
               <div class="full heading_s1">
                  <h2>WE ARE RIS</h2>
               </div>
               <div class="full">
                  <p class="large">Welcome to Royal International School, a beacon of hope and progress in our rural community. Founded by [NAME], our school was established with a singular vision: to transform the lives of villagers by bringing quality education closer to home. &nbsp;  <a class="blue_bt" href="{% url 'home:about' %}">About us</a></p>
                  
               </div>
            </div>
            {% comment %} <div class="col-md-12 hideam">
               <div class="about_img margin_top_30  text_align_center">
                  <img src="{% static 'home/images/ab_img.png' %}" alt="#" />
               </div>
            </div> {% endcomment %}
         </div>
      </div>
   </section>
   <!-- end about section -->

   <!-- section -->
   <section class="layout_padding section">
      <div class="container">
         <div class="row">
            <div class="col-lg-12 text_align_center">
               <div class="full heading_s1">
                  <h2>Our Programs</h2>
               </div>
               <div class="full">
                  <p class="large">
                     At Royal International School, we offer a diverse range of programs designed to meet the educational needs of our community. Our goal is to provide students with the knowledge and skills necessary to succeed in today’s world. At Royal International School, we are committed to providing a well-rounded education that prepares our students for the future. Join us and be a part of our vibrant learning community &nbsp;  <a class="blue_bt" href="{% url 'home:about' %}">Read More</a></p>
               </div>
            </div>
         </div>
         <div class="row">

           <div class="col-md-4 text_align_center">
              <div class="oval-image">
                <img class="img-responsive" src="{% static 'home/images/oval1.png' %}" alt="#" />
              </div>
              <h3>Formal Basic Education</h3>
              <p>Our Formal Basic Education program covers the essential subjects such as Mathematics, Science, English, and Social Studies. We follow a modern curriculum that encourages critical thinking, creativity, and problem-solving skills. Our experienced teachers use innovative teaching methods to make learning engaging and effective.</p>
           </div>  

           <div class="col-md-4 text_align_center">
              <div class="oval-image">
                <img class="img-responsive" src="{% static 'home/images/oval2.png' %}" alt="#" />
              </div>
              <h3>Special Literacy Programs</h3>
              <p>We believe that literacy is the foundation of all learning. Our Literacy Programs are designed to help students of all ages improve their reading and writing skills. These programs are especially beneficial for adults and young learners who need additional support to achieve literacy proficiency.</p>
           </div> 

           <div class="col-md-4 text_align_center">
              <div class="oval-image">
                <img class="img-responsive" src="{% static 'home/images/oval3.png' %}" alt="#" />
              </div>
              <h3>Vocational Training</h3>
              <p>In addition to academic education, we offer Vocational Training programs that equip students with practical skills for various trades and professions. These programs include training in areas such as agriculture, carpentry, tailoring, and information technology. Our vocational training aims to empower students with the skills needed to secure employment and contribute to the local economy.</p>
           </div> 

         </div>
         <div class="row">
            <div class="col-md-12">
               <div class="full center">
                   <a class="blue_bt" href="#">Read More</a>
               </div>
            </div>
         </div>
      </div>
   </section>
   <!-- end section -->


   <!-- section -->
   <section class="layout_padding section">
      <div class="container-fluid">
         <div class="row">
            <div class="col-lg-12 text_align_center">
               <div class="full heading_s1">
                  <h2>Our Success Stories</h2>
               </div>
               <div class="full">
                  <p class="large">Success stories concerning the schoool goes here.<br> Success stories like the kid who was given a scholarship by the house of assembly reprensentative</p>
               </div>
            </div>
            <div class="col-md-12 testimonial">
               <div class="full text_align_center">
                  <img src="{% static 'home/images/testimon.png' %}" alt="#" />
                  <h3><span class="theme_color_text">Student A B C</span><br><small>Student</small></h3>
               </div>
               <div class="full margin_top_30 text_align_center">
                 <h4>I was offered a scholarship</h4>
                 <p>The story of the students' scholarship can go here, <br> the story is to be written in first person pronoun.</p>
               </div>
            </div>
         </div>
     </div>
   </section>
   <!-- end section -->

   <!--section-->
   <section class="ACJ-blog" data-section="blog">
      <div class="ACJ-narrow-content">
          <div class="row">
              <div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
                  <span class="heading-meta">Read</span>
                  <h2 class="ACJ-heading">Recent Blog Post</h2>
              </div>
          </div>
          <div class="row">
              {% for post in recent_posts %}
              <div class="col-md-4 col-sm-6 animate-box" data-animate-effect="fadeInLeft">
                  <div class="card">
                      <h3 class="card-title"><a href="{{ post.image_url }}" >{{ post.title }}</a></h3>
                      {% if post.image %}
                          <a href="{{ post.image.url }}" target="_blank">
                              <!-- Make the image responsive -->
                              <img class="card-img-top img-fluid" 
                                   src="{{ post.image.url }}" 
                                   alt="{{ post.title }}">
                          </a>
                      {% elif post.image_url %}
                          <a href="{{ post.image_url }}" target="_blank">
                              <!-- External image fallback -->
                              <img class="card-img-top img-fluid" 
                                   src="{{ post.image_url }}" 
                                   alt="{{ post.title }}">
                          </a>
                      {% else %}
                          <p>No image available for this post.</p>
                      {% endif %}
                      <div class="desc">
                          <span><small>{{ post.date_published }}</small> | <small>{{ post.category }}</small> | <small><i class="icon-bubble3"></i> 4</small></span>
                          <p>{{ post.content }}</p>
                      </div>
                  </div>
              </div>
              {% endfor %}
          </div>
      </div>
  </section>
  
   <!--end section-->

  

       
     {% endblock sections %}
 